CREATE TABLE SONGS (
CHARTPLACEMENT INT PRIMARY KEY AUTO_INCREMENT,
weeksonchart INT,
song VARCHAR(50)
);
DROP TABLE songs;
DESCRIBE songs;
INSERT INTO songs (song, weeksonchart) VALUES ('Svag', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Blinding Lights', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Komplicerad', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Lev Nu Dö Sen', 2);
INSERT INTO songs (song, weeksonchart) VALUES ('Dance Monkey', 2);
INSERT INTO songs (song, weeksonchart) VALUES ('Roses (Imanbek Remix)', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('En Säng Av Rosor', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Rockstar (FEAT. Roddy Ricch)', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Savage Love (Laxed - Siren Beat)', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Pippi', 2);
INSERT INTO songs (song, weeksonchart) VALUES ('Mood (FEAT. Iann Dior)', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Someone You Loved', 2);
INSERT INTO songs (song, weeksonchart) VALUES ('Tills Mitt Hjärta Går Under', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('In Your Eyes', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Bedövning', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Head & Heart (FEAT. MNEK)', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Dip Dip', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Watermelon Sugar', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Kanske Var Vi Rätt Bra Ändå', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('The Box', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Breaking Me (FEAT. A7S)', 1);
INSERT INTO songs (song, weeksonchart) VALUES ("Don't Start Now", 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Young & Heartless', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Ice Cream', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Before You Go', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Bra För Dig', 2);
INSERT INTO songs (song, weeksonchart) VALUES ('Mi Amor (Blåmärkshårt) FEAT. Cherrie/Molly/Stor', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('XO', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Valhalla', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Some Say', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Hiphop N RnB', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Säg Mig Var Du Står', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Det Kommer Bli Bra', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Salt', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Kings & Queens', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Rosa Himmel', 2);
INSERT INTO songs (song, weeksonchart) VALUES ('You Broke Me First', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Death Bed (FEAT. Beabadoobee)', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Bruises', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Bad Guy', 2);
INSERT INTO songs (song, weeksonchart) VALUES ('Babblarnas Vaggvisa', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Mitten Av September', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('F.A.M.E (Leyley)', 2);
INSERT INTO songs (song, weeksonchart) VALUES ('Vem E Som Oss', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Bulletproof', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Fantasi', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Försent', 2);
INSERT INTO songs (song, weeksonchart) VALUES ('Ha Dig Igen', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Alla Våra Smeknamn', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Falling', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Toosie Slide', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Komma Över Dig', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Talking In My Sleep', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Frank Lucas', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('No Cap', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('If The World Was Ending (FEAT. Julia Michaels)', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Everything I Wanted', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Workin', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Say So', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Lemonade (FEAT. Don Toliver & Nav)', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Goliath', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Blueberry Faygo', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Memories', 2);
INSERT INTO songs (song, weeksonchart) VALUES ('Nån Av Oss', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Du Med Mig (Akustisk)', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Tesla', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Klär Av Dig', 2);
INSERT INTO songs (song, weeksonchart) VALUES ('Tillfälligheter', 2);
INSERT INTO songs (song, weeksonchart) VALUES ('E (Ventex) FEAT. Ture Brute', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Första Klivet', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Godzilla (FEAT Juice World', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Shallow', 3);
INSERT INTO songs (song, weeksonchart) VALUES ('Jag Mår Bra Nu (FEAT. Newkid)', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Move', 1);
INSERT INTO songs (song, weeksonchart) VALUES ("I Don't Care", 2);
INSERT INTO songs (song, weeksonchart) VALUES ('Like It Is', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('WAP (FEAT. Megan Thee Stallion)', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Ge Upp Igen', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Dance', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Gflow', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Sexcigg', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('For The Night (FEAT. Lil Baby & Dababy)', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Forever Yours (Avicii Tribute)', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Sånger Från Förut', 2);
INSERT INTO songs (song, weeksonchart) VALUES ('Circles', 2);
INSERT INTO songs (song, weeksonchart) VALUES ('Intentions (FEAT. Quavo)', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Hotspot', 2);
INSERT INTO songs (song, weeksonchart) VALUES ('Adore You', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('PT:1', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Passa Dig', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Higher Love', 2);
INSERT INTO songs (song, weeksonchart) VALUES ('Life Is Good (FEAT. Drake)', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Someone', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Hotel Walls', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Apelsinskal', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Sykepleierinnen (Sykehuset 2020)', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('What You Know Bout Love', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Break My Heart', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Whats Poppin (Remix) FEAT. Dababy/Tory/Lanez/Lil W', 1);
INSERT INTO songs (song, weeksonchart) VALUES ('Gav Allt', 1);


CREATE TABLE artists(
chartplacement INT PRIMARY KEY AUTO_INCREMENT,
artistName VARCHAR(25) NOT NULL,
featArtistName VARCHAR(25) DEFAULT ('No Feature')
);
DROP TABLE artists;
DESCRIBE artists;
INSERT INTO artists (artistName) VALUES ('Victor Leksell');
INSERT INTO artists (artistName) VALUES ('The Weeknd');
INSERT INTO artists (artistName) VALUES ('Miss Li');
INSERT INTO artists (artistName) VALUES ('Miss Li');
INSERT INTO artists (artistName) VALUES ('Tones And I');
INSERT INTO artists (artistName) VALUES ('Saint Jhn');
INSERT INTO artists (artistName) VALUES ('Darin');
INSERT INTO artists (artistName, featArtistName) VALUES ('Dababy', 'Roddy Ricch');
INSERT INTO artists (artistName, featArtistName) VALUES ('Jawsh 685','Jason Derulo');
INSERT INTO artists (artistName) VALUES ('Dree Low');
INSERT INTO artists (artistName, featArtistName) VALUES ('24KGOLDN', 'Iann Dior');
INSERT INTO artists (artistName) VALUES ('Lewis Capaldi');
INSERT INTO artists (artistName) VALUES ('Myra Granberg');
INSERT INTO artists (artistName) VALUES ('The Weeknd');
INSERT INTO artists (artistName) VALUES ('Victor Leksell');
INSERT INTO artists (artistName, featArtistName) VALUES ('Joel Corry', 'MNEK');
INSERT INTO artists (artistName, featArtistName) VALUES ('Dree Low', 'Owen');
INSERT INTO artists (artistName) VALUES ('Harry Styles');
INSERT INTO artists (artistName) VALUES ('Newkid');
INSERT INTO artists (artistName) VALUES ('Roddy Ricch');
INSERT INTO artists (artistName, featArtistName) VALUES ('Topic', 'A7S');
INSERT INTO artists (artistName) VALUES ('Dua Lipa');
INSERT INTO artists (artistName) VALUES ('Yasin');
INSERT INTO artists (artistName, featArtistName) VALUES ('Greekazo', 'Dree Low');
INSERT INTO artists (artistName) VALUES ('Lewis Capaldi');
INSERT INTO artists (artistName, featArtistName) VALUES ('Estraden', 'Victor Leksell');
INSERT INTO artists (artistName, featArtistName) VALUES ('Miriam Bryant', 'Cherrie/Molly/Stor');
INSERT INTO artists (artistName, featArtistName) VALUES ('Yasin', ' Dree Low');
INSERT INTO artists (artistName) VALUES ('Ringnes-Ronny');
INSERT INTO artists (artistName) VALUES ('Nea');
INSERT INTO artists (artistName) VALUES ('Yasin');
INSERT INTO artists (artistName, featArtistName) VALUES ('Zara Larsson', 'Carola');
INSERT INTO artists (artistName) VALUES ('Laleh');
INSERT INTO artists (artistName) VALUES ('Ava Max');
INSERT INTO artists (artistName) VALUES ('Ava Max');
INSERT INTO artists (artistName) VALUES ('Molly Sandén');
INSERT INTO artists (artistName) VALUES ('Tate McRae');
INSERT INTO artists (artistName, featArtistName) VALUES ('Powfu', 'Beabadoobee');
INSERT INTO artists (artistName) VALUES ('Lewis Capaldi');
INSERT INTO artists (artistName) VALUES ('Billie Eilish');
INSERT INTO artists (artistName) VALUES ('Babblarna');
INSERT INTO artists (artistName) VALUES ('HOV1');
INSERT INTO artists (artistName, featArtistName) VALUES ('Dani M', 'Simon Superti');
INSERT INTO artists (artistName) VALUES ('Anis Don Demina');
INSERT INTO artists (artistName) VALUES ('Dotter');
INSERT INTO artists (artistName) VALUES ('Victor Leksell');
INSERT INTO artists (artistName, featArtistName) VALUES ('1.CUZ', 'Greekazo');
INSERT INTO artists (artistName) VALUES ('Victor Leksell');
INSERT INTO artists (artistName) VALUES ('Molly Sandén');
INSERT INTO artists (artistName) VALUES ('Trevor Daniel');
INSERT INTO artists (artistName) VALUES ('Drake');
INSERT INTO artists (artistName) VALUES ('Norlie & KKV');
INSERT INTO artists (artistName) VALUES ('Paul Rey');
INSERT INTO artists (artistName) VALUES ('Einár');
INSERT INTO artists (artistName, featArtistName) VALUES ('Adel', 'Dree Low');
INSERT INTO artists (artistName, featArtistName) VALUES ('JP Saxe', 'Julia Michaels');
INSERT INTO artists (artistName) VALUES ('Billie Eilish');
INSERT INTO artists (artistName) VALUES ('Yasin');
INSERT INTO artists (artistName) VALUES ('Doja Cat');
INSERT INTO artists (artistName, featArtistName) VALUES ('Internet Money & Gunna', 'Don Toliver & Nav');
INSERT INTO artists (artistName) VALUES ('Smith & Thell');
INSERT INTO artists (artistName) VALUES ('Lil Mosey');
INSERT INTO artists (artistName) VALUES ('Maroon 5');
INSERT INTO artists (artistName) VALUES ('Miriam Bryant');
INSERT INTO artists (artistName) VALUES ('Miriam Bryant');
INSERT INTO artists (artistName, featArtistName) VALUES ('Macky', 'Einár');
INSERT INTO artists (artistName) VALUES ('Victor Leksell');
INSERT INTO artists (artistName) VALUES ('Veronica Maggio');
INSERT INTO artists (artistName, featArtistName) VALUES ('Albatraoz', 'Ture Brute');
INSERT INTO artists (artistName, featArtistName) VALUES ('Lellow', 'Sailboy');
INSERT INTO artists (artistName, featArtistName) VALUES ('Eminem', 'Juice World');
INSERT INTO artists (artistName, featArtistName) VALUES ('Lady Gaga', 'Bradley Cooper');
INSERT INTO artists (artistName, featArtistName) VALUES ('Molly Sandén', 'Newkid');
INSERT INTO artists (artistName) VALUES ('The Mamas');
INSERT INTO artists (artistName, featArtistName) VALUES ('Ed Sheeran', 'Justin Bieber');
INSERT INTO artists (artistName, featArtistName) VALUES ('Kygo', 'Zara Larsson');
INSERT INTO artists (artistName, featArtistName) VALUES ('Cadri B', 'Megan Thee Stallion');
INSERT INTO artists (artistName, featArtistName) VALUES ('Miriam Bryant', 'Yasin');
INSERT INTO artists (artistName, featArtistName) VALUES ('CLMD', 'Tungevaag');
INSERT INTO artists (artistName) VALUES ('LOV1');
INSERT INTO artists (artistName, featArtistName) VALUES ('Pop Smoke', 'Lil Baby & Dababy');
INSERT INTO artists (artistName, featArtistName) VALUES ('Kygo', 'Sandro Cavazza');
INSERT INTO artists (artistName) VALUES ('Gammal');
INSERT INTO artists (artistName) VALUES ('Post Malone');
INSERT INTO artists (artistName, featArtistName) VALUES ('Justin Bieber','Quavo');
INSERT INTO artists (artistName, featArtistName) VALUES ('Greekazo', 'Dnoteondabeat');
INSERT INTO artists (artistName) VALUES ('Harry Styles');
INSERT INTO artists (artistName) VALUES ('Yasin');
INSERT INTO artists (artistName) VALUES ('Miriam Bryant');
INSERT INTO artists (artistName, featArtistName) VALUES ('Kygo', 'Whitney Houston');
INSERT INTO artists (artistName, featArtistName) VALUES ('Future', 'Drake');
INSERT INTO artists (artistName) VALUES ('Jubël');
INSERT INTO artists (artistName) VALUES ('Smith & Thell');
INSERT INTO artists (artistName, featArtistName) VALUES ('Tjuvjakt', 'Newkid');
INSERT INTO artists (artistName) VALUES ('El Papi');
INSERT INTO artists (artistName) VALUES ('Pop Smoke');
INSERT INTO artists (artistName) VALUES ('Dua Lipa');
INSERT INTO artists (artistName, featArtistName) VALUES ('Jack Harlow', 'Dababy/Tory/Lanez/Lil W');
INSERT INTO artists (artistName, featArtistName) VALUES ('Jireel', 'Victor Leksell');
SELECT * FROM artists;

CREATE TABLE chartingInfo(
currentChartPlacement int primary key auto_increment,
song varchar(100),
weeksOnCharts INT,
higestChartPlacement INT,
foreign key (song) references songs (song)
);
